# Generated by Django 3.2.12 on 2022-03-09 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('name', models.CharField(default='Доска', max_length=100, primary_key=True, serialize=False, verbose_name='Название доски для заметок')),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('num_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='e-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Заметка', max_length=100, verbose_name='Название заметки')),
                ('textn', models.TextField(blank=True, verbose_name='Текст заметки')),
                ('urln', models.URLField(blank=True, verbose_name='Вставить ссылку на объект')),
                ('available', models.BooleanField(verbose_name='Скрыть объект для других пользователей')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.folder', verbose_name='Название папки')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
