/* eslint-disable */
export const ADD_NOTE = 'ADD_NOTE'
export const REMOVE_NOTE = 'REMOVE_NOTE'
export const SET_NOTES = 'SET_NOTES'
export const ADD_FOLDER = 'ADD_FOLDER'
export const REMOVE_FOLDER = 'REMOVE_FOLDER'
export const SET_FOLDERS = 'SET_FOLDERS'
export const ADD_FILE = 'ADD_FILE'
export const REMOVE_FILE = 'REMOVE_FILE'
export const SET_FILES = 'SET_FILES'
export const SET_FOLDERV = 'SET_FOLDERV'